from gan_enc import GanEnc
from gan_gen import GanGen
from gan_dis import GanDis
from ae_enc import AutoEnc
from clf_enc import Clf
from floss_gen import FLoss
from infogan_dis import InfoDis
from infogan_gen import InfoGen
from vggae import VGGAutoEnc